version: "3"
name: "forensic"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "${PG_HOST_PORT:-6543}:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: forensic_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    ports:
      - "${PGADMIN_HOST_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
